### ISSUE TITLE
Todo list does not work

### ISSUE THREAD

**Issue by 215566435** [showdownjs/showdown#506]
Hi there.

I have been using Showdown for a while, here is what i found in v1.8.6

```js
const c = new showdown.Converter();

c.makeHtml(source);
```

input
```
- [x] todo
- [x] todo
- [x] todo
- [x] todo
- [x] todo
- [x] todo

```

output

```
<li>[x] todo</li>
<li>[x] todo</li>
<li>[x] todo</li>
<li>[x] todo</li>
<li>[x] todo</li>
<li>[x] todo</li>
<li>[x] todo</li>

```

I want a todo-list but got something like this.

just a simple usage , any help?

thanks.

**Comment by JonSn0w** [comment]
If you want to be able to use checklists, you have to set the `tasklists` option to true.
for more info on this and other options I would suggest you check out the [wiki page](https://github.com/showdownjs/showdown/wiki/Showdown-options#tasklists).

**Comment by 215566435** [comment]
@JonSn0w oh, great.

Thanks for reply.

I will check them out.

**Comment by tivie** [comment]
Thanks @JonSn0w

**Comment by louagej** [comment]
I have the same issue
My option is set to true
`var converter = new showdown.Converter({
    simplifiedAutoLink: true,
    tasklists: true,
    tables: true,
    strikethrough: true
}),
    text = data,
    html = converter.makeHtml(text);`

In my markdown, it show up correct like this:
2. Takslist

- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request

But the **html-output** shows like this:
![image](https://user-images.githubusercontent.com/7229592/58094612-65559680-7bd1-11e9-972e-e9889215cef1.png)
